import type { ERSchema, ERField } from '@/types/er'

function dialectKey(databaseType?: string): string {
  if (!databaseType) return 'generic'
  const dk = databaseType.toLowerCase().split(/[+]/)[0]
  if (dk === 'postgres' || dk === 'pgsql') return 'postgresql'
  return dk
}

function quote(name: string, dk: string): string {
  if (dk === 'mysql' || dk === 'mariadb') return `\`${name}\``
  if (dk === 'postgresql') return `"${name}"`
  if (dk === 'mssql') return `[${name}]`
  return `"${name}"`
}

function autoIncrementClause(dk: string): string {
  if (dk === 'postgresql') return ''
  if (dk === 'sqlite') return 'AUTOINCREMENT'
  if (dk === 'mssql') return 'IDENTITY(1,1)'
  return 'AUTO_INCREMENT'
}

function mapType(field: ERField, dk: string): string {
  if (!field.isAutoIncrement) return field.type
  if (dk === 'postgresql') {
    const upper = field.type.toUpperCase()
    if (upper === 'INT' || upper === 'INTEGER') return 'SERIAL'
    if (upper === 'BIGINT') return 'BIGSERIAL'
    if (upper === 'SMALLINT') return 'SMALLSERIAL'
    return field.type
  }
  return field.type
}

function formatField(field: ERField, dk: string): string {
  const parts: string[] = []
  const type = mapType(field, dk)
  parts.push(`  ${quote(field.name, dk)} ${type}`)
  if (!field.nullable) parts.push('NOT NULL')
  if (field.isPrimaryKey) parts.push('PRIMARY KEY')
  if (field.isUnique && !field.isPrimaryKey) parts.push('UNIQUE')
  if (field.isAutoIncrement) {
    const ac = autoIncrementClause(dk)
    if (ac) parts.push(ac)
  }
  if (field.defaultValue !== undefined && field.defaultValue !== '') {
    parts.push(`DEFAULT ${field.defaultValue}`)
  }
  if (field.comment) {
    if (dk === 'mysql' || dk === 'mariadb') {
      parts.push(`COMMENT '${field.comment.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`)
    }
  }
  return parts.join(' ')
}

export function exportAsSQL(schema: ERSchema): string {
  const dk = dialectKey(schema.databaseType)
  const lines: string[] = []
  lines.push(`-- Generated by ERBeauti`)
  lines.push(`-- Schema: ${schema.name}`)
  if (schema.databaseType) {
    lines.push(`-- Dialect: ${schema.databaseType}`)
  }
  lines.push('')

  for (const table of schema.tables) {
    lines.push(`CREATE TABLE ${quote(table.name, dk)} (`)
    const fieldLines = table.fields.map((f) => formatField(f, dk))
    lines.push(fieldLines.join(',\n'))
    lines.push(')')
    if (dk === 'mysql' || dk === 'mariadb') {
      lines.push('ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;')
    } else {
      lines.push(';')
    }
    lines.push('')
  }

  for (const rel of schema.relationships) {
    const srcField = rel.sourceFieldId.split('.')[1] ?? ''
    const tgtField = rel.targetFieldId.split('.')[1] ?? ''
    lines.push(
      `ALTER TABLE ${quote(rel.sourceTableId, dk)} ADD FOREIGN KEY (${quote(srcField!, dk)}) REFERENCES ${quote(rel.targetTableId, dk)} (${quote(tgtField!, dk)});`,
    )
  }

  return lines.join('\n')
}
